### ISSUE TITLE
If the footnotes are collapsed, the footnotes will not be loaded. "`undefined`"

### ISSUE THREAD

**Issue by YU000jp** [b-yp/logseq-preview-footnote#7]
[Problem] If it is collapsed, the DOM cannot be retrieved.
  1. Add an option to expand the parent blocks

If it can't do
  1. Add it to the description

I might also make a pull request. Thank you for creating this plugin. Looks good as a workflow.

**Comment by b-yp** [comment]
This is indeed a problem. I've been a bit busy these days, but I'll think about how to implement it in a couple of days. If you can submit the code, it would be my pleasure. In any case, thank you very much.

**Comment by YU000jp** [comment]
I'll start working on it now.
